export const SAMPLE_LIMITS = {
  SAMPLE_ID: 15,
  USER_ID: 15,
  MODE_OF_SAMPLE: 15,
  SAMPLE_TYPE: 15,
  SAMPLE_SOURCE: 15,
  MAIN_SOURCE: 15,
  CUSTOMER: 25,
  SAMPLE_DATE_OF_ISSUE: 25,
  HABITATION: 15,
  SAMPLE_TEST_VILLAGE: 25,
  SAMPLE_TEST_TALUKA: 25,
  SAMPLE_TEST_DISTRICT: 25,
  SAMPLE_TEST_ADDRESS: 40,
  SAMPLE_TEST_LATITUDE: 15,
  SAMPLE_TEST_LONGITUDE: 15,
  SAMPLE_SUBMITTED_DATE: 25,
} as const;

